class Product {
  final String id;
  final String title;
  final String slug;
  final String category;
  final String subCategory;
  final String description;
  final String shortDescription;
  final double price;
  final double compareAtPrice;
  final String sku;
  final int warehouseStock;
  final bool isAvailable;
  final bool isFeatured;
  final double averageRating;
  final int reviewCount;
  final String imageUrl;
  final List<String> tags;

  Product({
    required this.id,
    required this.title,
    required this.slug,
    required this.category,
    required this.subCategory,
    required this.description,
    required this.shortDescription,
    required this.price,
    required this.compareAtPrice,
    required this.sku,
    required this.warehouseStock,
    required this.isAvailable,
    required this.isFeatured,
    required this.averageRating,
    required this.reviewCount,
    required this.imageUrl,
    required this.tags,
  });

  factory Product.fromJson(Map<String, dynamic> json) {
    String img = 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=800';
    if (json['images'] != null && json['images'] is List && (json['images'] as List).isNotEmpty) {
      var first = json['images'][0];
      if (first is Map && first['url'] != null) {
        img = first['url'];
      } else if (first is String) {
        img = first;
      }
    } else if (json['imageUrl'] != null) {
      img = json['imageUrl'];
    }

    return Product(
      id: json['id'] ?? json['_id'] ?? '',
      title: json['title'] ?? json['name'] ?? '',
      slug: json['slug'] ?? '',
      category: json['category'] ?? 'General',
      subCategory: json['subCategory'] ?? '',
      description: json['description'] ?? '',
      shortDescription: json['shortDescription'] ?? json['description'] ?? '',
      price: (json['price'] ?? 0.0).toDouble(),
      compareAtPrice: (json['compareAtPrice'] ?? 0.0).toDouble(),
      sku: json['sku'] ?? 'SKU-000',
      warehouseStock: json['warehouseStock'] ?? json['stock'] ?? 0,
      isAvailable: json['isAvailable'] ?? true,
      isFeatured: json['isFeatured'] ?? false,
      averageRating: (json['averageRating'] ?? 4.8).toDouble(),
      reviewCount: json['reviewCount'] ?? 100,
      imageUrl: img,
      tags: json['tags'] != null ? List<String>.from(json['tags']) : [],
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'title': title,
    'slug': slug,
    'category': category,
    'subCategory': subCategory,
    'description': description,
    'shortDescription': shortDescription,
    'price': price,
    'compareAtPrice': compareAtPrice,
    'sku': sku,
    'warehouseStock': warehouseStock,
    'isAvailable': isAvailable,
    'isFeatured': isFeatured,
    'averageRating': averageRating,
    'reviewCount': reviewCount,
    'imageUrl': imageUrl,
    'tags': tags,
  };
}

final List<Product> INITIAL_PRODUCTS = [
  Product(
    id: 'prod_1',
    title: 'Callebaut Dark Chocolate 1kg (54.5% Cocoa)',
    slug: 'callebaut-dark-chocolate-1kg',
    category: 'Ingredients',
    subCategory: 'Chocolate',
    description: 'Rich and balanced dark Belgian chocolate callets (54.5% cocoa) ideal for baking, ganache, mousse, and desserts.',
    shortDescription: 'Balanced 54.5% Belgian dark chocolate callets with rich cocoa body.',
    price: 1250.0,
    compareAtPrice: 1500.0,
    sku: 'ING-CHOC-001',
    warehouseStock: 85,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.9,
    reviewCount: 320,
    imageUrl: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=800',
    tags: ['chocolate', 'ingredients', 'callebaut', 'belgian'],
  ),
  Product(
    id: 'prod_2',
    title: 'Callebaut Milk Chocolate 1kg (33.6% Cocoa)',
    slug: 'callebaut-milk-chocolate-1kg',
    category: 'Ingredients',
    subCategory: 'Chocolate',
    description: 'Creamy Belgian milk chocolate callets with deep caramel and cocoa undertones. Perfect for pralines and cakes.',
    shortDescription: 'Creamy 33.6% Belgian milk chocolate callets with caramel notes.',
    price: 1255.0,
    compareAtPrice: 1480.0,
    sku: 'ING-CHOC-002',
    warehouseStock: 60,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.8,
    reviewCount: 210,
    imageUrl: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=800',
    tags: ['chocolate', 'ingredients', 'milk-chocolate'],
  ),
  Product(
    id: 'prod_3',
    title: 'Callebaut Velvet White Chocolate 1kg (33.1% Cocoa)',
    slug: 'callebaut-white-chocolate-1kg',
    category: 'Ingredients',
    subCategory: 'Chocolate',
    description: 'Silky smooth Belgian white chocolate with rich milk taste and delicate sweetness for exquisite baking and enrobing.',
    shortDescription: 'Silky smooth 33.1% Belgian white chocolate callets.',
    price: 1350.0,
    compareAtPrice: 1600.0,
    sku: 'ING-CHOC-003',
    warehouseStock: 45,
    isAvailable: true,
    isFeatured: false,
    averageRating: 4.9,
    reviewCount: 185,
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800',
    tags: ['chocolate', 'white-chocolate', 'callebaut'],
  ),
  Product(
    id: 'prod_4',
    title: 'Anchor Whipping Cream 1L (Pure Dairy)',
    slug: 'anchor-whipping-cream-1l',
    category: 'Ingredients',
    subCategory: 'Dairy',
    description: 'Ultra-stable 35.5% fat pure New Zealand dairy whipping cream. Yields magnificent whipped peaks for pastries.',
    shortDescription: 'Pure New Zealand whipping cream with 35.5% milk fat.',
    price: 780.0,
    compareAtPrice: 900.0,
    sku: 'ING-DAIRY-004',
    warehouseStock: 140,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.9,
    reviewCount: 450,
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800',
    tags: ['dairy', 'whipping-cream', 'anchor'],
  ),
  Product(
    id: 'prod_5',
    title: 'Anchor Unsalted Butter 450g',
    slug: 'anchor-unsalted-butter-450g',
    category: 'Ingredients',
    subCategory: 'Dairy',
    description: 'Made from 100% pure New Zealand pasture-fed cow milk. Essential for flaky croissants and rich cakes.',
    shortDescription: '100% Pure grass-fed New Zealand unsalted butter.',
    price: 450.0,
    compareAtPrice: 520.0,
    sku: 'ING-DAIRY-005',
    warehouseStock: 110,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.8,
    reviewCount: 290,
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=800',
    tags: ['butter', 'dairy', 'anchor'],
  ),
  Product(
    id: 'prod_6',
    title: 'Saf-Instant Red Dry Yeast 500g',
    slug: 'saf-instant-yeast-500g',
    category: 'Flour & Yeast',
    subCategory: 'Yeast',
    description: 'French premium instant dry yeast for bread, brioche, croissants, and artisan pizza dough.',
    shortDescription: 'Premium French instant dry yeast for high-performance baking.',
    price: 380.0,
    compareAtPrice: 450.0,
    sku: 'ING-YEAST-006',
    warehouseStock: 200,
    isAvailable: true,
    isFeatured: false,
    averageRating: 4.9,
    reviewCount: 160,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    tags: ['yeast', 'flour-yeast', 'baking'],
  ),
  Product(
    id: 'prod_7',
    title: 'French T55 Patisserie Flour 1kg',
    slug: 'french-t55-patisserie-flour-1kg',
    category: 'Flour & Yeast',
    subCategory: 'Flour',
    description: 'Imported French wheat flour with optimal gluten strength for croissants, puff pastry, and baguettes.',
    shortDescription: 'Authentic French T55 wheat flour for fine pastries.',
    price: 320.0,
    compareAtPrice: 380.0,
    sku: 'ING-FLOUR-007',
    warehouseStock: 175,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.8,
    reviewCount: 230,
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800',
    tags: ['flour', 't55', 'french-flour'],
  ),
  Product(
    id: 'prod_8',
    title: 'Nielsen-Massey Pure Vanilla Extract 118ml',
    slug: 'nielsen-massey-vanilla-extract',
    category: 'Flavours',
    subCategory: 'Extracts',
    description: 'Madagascar Bourbon pure vanilla extract cold-extracted for maximum flavor intensity in cakes and custard.',
    shortDescription: 'Pure Madagascar Bourbon vanilla extract for gourmet baking.',
    price: 1850.0,
    compareAtPrice: 2100.0,
    sku: 'ING-FLAV-008',
    warehouseStock: 50,
    isAvailable: true,
    isFeatured: false,
    averageRating: 5.0,
    reviewCount: 95,
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800',
    tags: ['vanilla', 'extract', 'flavours'],
  ),
  Product(
    id: 'prod_9',
    title: 'Professional Perforated Tart Ring Set (6 Pcs)',
    slug: 'perforated-tart-ring-set-6pcs',
    category: 'Tools',
    subCategory: 'Baking Tools',
    description: 'Micro-perforated stainless steel tart rings for crisp, perfectly browned pastry crusts.',
    shortDescription: 'Stainless steel micro-perforated pastry tart rings.',
    price: 890.0,
    compareAtPrice: 1100.0,
    sku: 'TOOL-TART-009',
    warehouseStock: 90,
    isAvailable: true,
    isFeatured: false,
    averageRating: 4.7,
    reviewCount: 115,
    imageUrl: 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=800',
    tags: ['tart-ring', 'tools', 'baking-tools'],
  ),
  Product(
    id: 'prod_10',
    title: 'Premium Silicone Spatula Set (Set of 2)',
    slug: 'premium-silicone-spatula-set-of-2',
    category: 'Tools',
    subCategory: 'Baking Tools',
    description: 'Heat-resistant up to 260°C seamless food-grade silicone spatulas for macaron folding and chocolate melting.',
    shortDescription: 'Heat-resistant seamless silicone spatulas.',
    price: 450.0,
    compareAtPrice: 600.0,
    sku: 'TOOL-SPT-010',
    warehouseStock: 180,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.9,
    reviewCount: 280,
    imageUrl: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800',
    tags: ['spatula', 'silicone', 'tools'],
  ),
  Product(
    id: 'prod_11',
    title: 'KitchenAid Artisan Stand Mixer 4.8L (Empire Red)',
    slug: 'kitchenaid-artisan-stand-mixer-4-8l',
    category: 'Tools',
    subCategory: 'Equipment',
    description: 'Heavy-duty 10-speed tilt-head stand mixer with stainless steel bowl, dough hook, and wire whip.',
    shortDescription: 'Heavy-duty 4.8L tilt-head artisan stand mixer in Empire Red.',
    price: 42500.0,
    compareAtPrice: 48000.0,
    sku: 'TOOL-MIX-011',
    warehouseStock: 15,
    isAvailable: true,
    isFeatured: true,
    averageRating: 5.0,
    reviewCount: 78,
    imageUrl: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=800',
    tags: ['kitchenaid', 'mixer', 'tools', 'equipment'],
  ),
];

